#@title L0K1 COLAB
 
import random, string, urllib.request, json, getpass, os
 
#Generate root password
password = ''.join(random.choice(string.ascii_letters + string.digits) for i in range(20))
 
#Download ngrok
! wget -q -c -nc https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
! unzip -qq -n ngrok-stable-linux-amd64.zip
 
#Setup sshd
! apt-get install -qq -o=Dpkg::Use-Pty=0 openssh-server pwgen > /dev/null
 
#Set root password
! echo root:$password | chpasswd
! mkdir -p /var/run/sshd
! echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
! echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
! echo "LD_LIBRARY_PATH=/usr/lib64-nvidia" >> /root/.bashrc
! echo "export LD_LIBRARY_PATH" >> /root/.bashrc
 
#Run sshd
get_ipython().system_raw('/usr/sbin/sshd -D &')
 
#Ask token
os.system('cls')
print('\u001b[32;1m$$\       $$$$$$\  $$\   $$\   $$\         $$$$$$$\   $$$$$$\ $$$$$$$$\ ')
print('\u001b[32;1m$$ |     $$$ __$$\ $$ | $$  |$$$$ |        $$  __$$\ $$$ __$$\\__ $$ __|')
print('\u001b[32;1m$$ |     $$$$\ $$ |$$ |$$  / \_$$ |        $$ |  $$ |$$$$\ $$ |  $$ |   ')
print('\u001b[32;1m$$ |     $$\$$\$$ |$$$$$  /    $$ |        $$$$$$$\ |$$\$$\$$ |  $$ |   ')
print('\u001b[32;1m$$ |     $$ \$$$$ |$$  $$<     $$ |        $$  __$$\ $$ \$$$$ |  $$ |   ')
print('\u001b[32;1m$$ |     $$ |\$$$ |$$ |\$$\    $$ |        $$ |  $$ |$$ |\$$$ |  $$ |   ')
print('\u001b[32;1m$$$$$$$$\\$$$$$$   /$$ | \$$\ $$$$$$\       $$$$$$$  |\$$$$$$ /   $$ |   ')
print('\u001b[32;1m\________|\______/ \__|  \__|\______|      \_______/  \______/   \__|   ')
print("\nCopie o token da pagina https://dashboard.ngrok.com/auth")
print("Ps:Em caso de erro clique em executar o código novamente na colab!")
print("\nDigite o token abaixo:")
authtoken = getpass.getpass()
 
 
#Create tunnel
get_ipython().system_raw('./ngrok authtoken $authtoken && ./ngrok tcp 22 &')
 
#Get public address and print connect command
with urllib.request.urlopen('http://localhost:4040/api/tunnels') as response:
  data = json.loads(response.read().decode())
  (host, port) = data['tunnels'][0]['public_url'][6:].split(':')
  print(f'SSH command: ssh -p{port} root@{host}')
 
#Print root password
print(f'Root password: {password}')
